apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginxpod
spec:
  containers:
  - name: myappinginx
    image: nginxdemos/hello:0.4
    ports:
      - containerPort: 80
