apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxr-rs
  labels:
    app: mywebapp
    env: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      proj: processing #match with template.metadata.label key
  template:
    metadata:
      labels:
        proj: processing
    spec:
      containers:
        - name: myapp
          image: nginx
